apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-backup-script
  namespace: default
data:
  backup.sh: |
    #!/bin/bash
    # 数据库连接信息
    DB_HOST=postgresdb
    DB_NAME=postgresdb
    DB_USER=$POSTGRES_USER
    DB_PASSWORD=$POSTGRES_PASSWORD

    # 备份文件存储路径
    BACKUP_DIR=/backups
    mkdir -p $BACKUP_DIR

    # 当前时间戳
    TIMESTAMP=$(date +"%Y%m%d%H%M%S")

    # 备份文件名
    BACKUP_FILE="$BACKUP_DIR/postgresql_backup_$TIMESTAMP.sql"

    # 执行备份命令
    PGPASSWORD=$DB_PASSWORD pg_dump -h $DB_HOST -U $DB_USER -d $DB_NAME -t test > $BACKUP_FILE

    # 删除旧的备份文件，保留最近10次备份
    cd $BACKUP_DIR
    ls -t | tail -n +11 | xargs rm --

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: postgres-backup:latest
            envFrom:
              - configMapRef:
                  name: postgres-config
            command: ["sh","-c","/home/backup.sh"]
            volumeMounts:
            - name: backup-volume
              mountPath: /backups
            - name: postgresql-script
              mountPath: /home
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            hostPath:
              path: /mnt/data/backup
          - name: postgresql-script
            configMap:
              name: postgresql-backup-script
              items:
              - key: backup.sh
                path: backup.sh