apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-sql-config
  namespace: default
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS mydatabase;
    \c mydatabase;
    CREATE TABLE test (
      id SERIAL PRIMARY KEY,
      name VARCHAR(50) NOT NULL,
      age INT
    );
    DO $$
    DECLARE
      i INT;
    BEGIN
      FOR i IN 1..1000 LOOP
        INSERT INTO test (name, age) VALUES
        ('Name' || i, ROUND(RANDOM() * 100));
      END LOOP;
    END $$;
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-init
spec:
  template:
    metadata:
      name: postgresql-init
    spec:
      containers:
      - name: init-sql
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: postgresql-initdb
          mountPath: /app/config
        command: ["sh","-c","psql -U postgres -h myapp-postgresql-nodeport -f /app/config/init.sql"]
      volumes:
      - name: postgresql-initdb
        configMap:
          name: postgresql-initdb-sql-config
          items:
          - key: initdb.sql
            path: init.sql
      restartPolicy: OnFailure