apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  type: NodePort
  ports:
  - name: data
    port: 9000
    targetPort: 9000
    protocol: TCP
    nodePort: 39000
  - name: console
    port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 39001
  selector:
    app: minio
