apiVersion: v1
kind: Service
metadata:
  name: myapp-postgresql-headless
  labels:
    app: postgresql
    release: "myapp"
spec:
  clusterIP: None
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  selector:
    app: postgresql
    release: "myapp"

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-postgresql-nodeport
  labels:
    app: postgresql
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql
  selector:
   app: postgresql