apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgresql
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin12345
  PGDATA: "/var/lib/postgresql/data/pgdata"